### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by odonnellryan** [twilio/twilio-python#120]
Hello! I'm getting a strange error, though the texts send perfectly fine!

C:\Python27\python.exe testing_database.py
Traceback (most recent call last):
  File "testing_database.py", line 9, in <module>
    body="Hello there!")
  File "C:\Python27\lib\site-packages\twilio-3.5.0-py2.7.egg\twilio\rest\resources\sms_messages.py", line 95, in create
    return self.create_instance(kwargs)
  File "C:\Python27\lib\site-packages\twilio-3.5.0-py2.7.egg\twilio\rest\resources\base.py", line 236, in create_instance
    return self.load_instance(instance)
  File "C:\Python27\lib\site-packages\twilio-3.5.0-py2.7.egg\twilio\rest\resources\base.py", line 289, in load_instance
    instance.load(data)
  File "C:\Python27\lib\site-packages\twilio-3.5.0-py2.7.egg\twilio\rest\resources\base.py", line 158, in load
    entries[key] = parse_rfc2822_date(entries[key])
  File "C:\Python27\lib\site-packages\twilio-3.5.0-py2.7.egg\twilio\rest\resources\util.py", line 51, in parse_rfc2822_date
    return datetime.datetime(*parsedate(s)[:6])
TypeError: 'NoneType' object has no attribute '**getitem**'

Process finished with exit code 1

That's the error code, unsure of what is going wrong! 

twilio==3.5.0
Flask==0.9
Python 2.7.5

Only happened after upgrading from 3.4.5 to 3.5

Thanks! Let me know how I can help.

Ryan
